### ISSUE TITLE
Vicious circle on first run...

### ISSUE THREAD

**Issue by Hades32** [eriklupander/tradfri-go#1]
From the readme, this should work:

```
./tradfri-go -authenticate -clientId blubber -psk secretsecret -gateway 192.168.178.157
Could not find psk.key in current directory, trying to use env-vars CLIENT_ID and PRE_SHARED_KEY instead
panic: Unable to resolve PRE_SHARED_KEY from env-var or psk.key file
```

But it fails... Looking at the code I also can't see how viper should be able to get the relation between -psk and PRE_SHARED_KEY...

**Comment by Hades32** [comment]
I can of course workaround this by setting the env vars and creating that file by hand, but then I get an timeout connecting to the gateway. But because of above errors I'm not sure if that's just because the setup was not done correctly or if I have a second issue.

**Comment by eriklupander** [comment]
Thanks for the report, I probably messed up the initialization when running the -authenticate code path. Will take a look ASAP.

**Comment by eriklupander** [comment]
I've fixed the problem, thanks for reporting it!

(As a side note - one can only perform the key exchange exactly once per "CLIENT_ID". Subsequent attempts  returns a CoAP error code (5.00 or 4.00, can't remember which). However, it seems to be OK to use different CLIENT_IDs, the gateway "remembers" previously issued tokens per CLIENT_ID.)

**Comment by Hades32** [comment]
Awesome, thank you! Works as advertised :)

And the new hint about the timeout was already helpful :D 

Great project!
